version: '3.7'

services:
  app:
    build: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s npm start
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_started

  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init_database.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
